### ISSUE TITLE
Getting HTTP 403 Forbidden error while connecting socket with apollo subscription.

### ISSUE THREAD

**Issue by nikunjmi** [ArcBlock/arcblock-android-sdk#45]
I have a requirement like first I need to connect socket and then call apollo subscription graphQL API calls so first I created ABCoreKitClient as per quickstart in SDK and try to do apollo subscription with socket connection But getting HTTP 403 Forbidden error for the socket connection.

I already passed all required header param and okhttpclient in apollo client using the builder class of ABCoreKitClient.

Can you please help me to how to do this socket connection with apollo subscription API.

Thanks.

**Comment by NateRobinson** [comment]
Which endpoint do you want to connect? the 403 error is sent by the server, maybe you need pass right token with right way to the server endpoint.
